# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobility.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emobility.proto\x12\x08mobility\"\x18\n\nIdentifier\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x08Position\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x01\"L\n\x07Vehicle\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.mobility.Identifier\x12\x1f\n\x03pos\x18\x02 \x01(\x0b\x32\x12.mobility.Position\"@\n\rSearchRequest\x12\x1f\n\x03pos\x18\x01 \x01(\x0b\x32\x12.mobility.Position\x12\x0e\n\x06radius\x18\x02 \x01(\x01\"n\n\x0eHistoryRequest\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.mobility.Identifier\x12\x1d\n\x05start\x18\x02 \x01(\x0b\x32\x0e.mobility.Time\x12\x1b\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x0e.mobility.Time\"\x1f\n\x0bPutResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xe7\x01\n\x08Mobility\x12\x31\n\x03Put\x12\x11.mobility.Vehicle\x1a\x15.mobility.PutResponse\"\x00\x12\x31\n\x03Get\x12\x14.mobility.Identifier\x1a\x12.mobility.Position\"\x00\x12\x38\n\x06Search\x12\x17.mobility.SearchRequest\x1a\x11.mobility.Vehicle\"\x00\x30\x01\x12;\n\x07History\x12\x18.mobility.HistoryRequest\x1a\x12.mobility.Position\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobility_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDENTIFIER._serialized_start=28
  _IDENTIFIER._serialized_end=52
  _POSITION._serialized_start=54
  _POSITION._serialized_end=101
  _TIME._serialized_start=103
  _TIME._serialized_end=123
  _VEHICLE._serialized_start=125
  _VEHICLE._serialized_end=201
  _SEARCHREQUEST._serialized_start=203
  _SEARCHREQUEST._serialized_end=267
  _HISTORYREQUEST._serialized_start=269
  _HISTORYREQUEST._serialized_end=379
  _PUTRESPONSE._serialized_start=381
  _PUTRESPONSE._serialized_end=412
  _MOBILITY._serialized_start=415
  _MOBILITY._serialized_end=646
# @@protoc_insertion_point(module_scope)
