# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mobility_pb2 as mobility__pb2


class MobilityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/mobility.Mobility/Put',
                request_serializer=mobility__pb2.Vehicle.SerializeToString,
                response_deserializer=mobility__pb2.PutResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/mobility.Mobility/Get',
                request_serializer=mobility__pb2.Identifier.SerializeToString,
                response_deserializer=mobility__pb2.Position.FromString,
                )
        self.Search = channel.unary_stream(
                '/mobility.Mobility/Search',
                request_serializer=mobility__pb2.SearchRequest.SerializeToString,
                response_deserializer=mobility__pb2.Vehicle.FromString,
                )
        self.History = channel.unary_stream(
                '/mobility.Mobility/History',
                request_serializer=mobility__pb2.HistoryRequest.SerializeToString,
                response_deserializer=mobility__pb2.Position.FromString,
                )


class MobilityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobilityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=mobility__pb2.Vehicle.FromString,
                    response_serializer=mobility__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=mobility__pb2.Identifier.FromString,
                    response_serializer=mobility__pb2.Position.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=mobility__pb2.SearchRequest.FromString,
                    response_serializer=mobility__pb2.Vehicle.SerializeToString,
            ),
            'History': grpc.unary_stream_rpc_method_handler(
                    servicer.History,
                    request_deserializer=mobility__pb2.HistoryRequest.FromString,
                    response_serializer=mobility__pb2.Position.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mobility.Mobility', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mobility(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobility.Mobility/Put',
            mobility__pb2.Vehicle.SerializeToString,
            mobility__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mobility.Mobility/Get',
            mobility__pb2.Identifier.SerializeToString,
            mobility__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mobility.Mobility/Search',
            mobility__pb2.SearchRequest.SerializeToString,
            mobility__pb2.Vehicle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mobility.Mobility/History',
            mobility__pb2.HistoryRequest.SerializeToString,
            mobility__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
